export const FETCH_ARTICLES_SUCCESS = "FETCH_ARTICLES_SUCCESS";
export const SELECTED_ARTICLE_FETCH = "SELECTED_ARTICLE_FETCH";
export const SELECTED_ARTICLE_SUCCESS = "SELECTED_ARTICLE_SUCCESS";
export const POST_NEW_ARTICLE_SUCCESS = "POST_NEW_ARTICLE_SUCCESS";
export const POST_NEW_ARTICLE_FAILURE = "POST_NEW_ARTICLE_FAILURE";
export const PUT_UPDATE_ARTICLE_SUCCESS = "PUT_UPDATE_ARTICLE_SUCCESS";
export const PUT_UPDATE_ARTICLE_FAILURE = "PUT_UPDATE_ARTICLE_FAILURE";
export const DELETE_ARTICLE_SUCCESS = "DELETE_ARTICLE_SUCCESS";
export const DELETE_ARTICLE_FAILURE = "DELETE_ARTICLE_FAILURE";
export const POST_FAVORITE_ARTICLE_SUCCESS = "POST_FAVORITE_ARTICLE_SUCCESS";
export const POST_FAVORITE_ARTICLE_FAILURE = "POST_FAVORITE_ARTICLE_FAILURE";

export const LOADER_DISPLAY_ON = "LOADER_DISPLAY_ON";
export const LOADER_DISPLAY_OFF = "LOADER_DISPLAY_OFF";

export const ERROR_DISPLAY_ON = "ERROR_DISPLAY_ON";
export const ERROR_DISPLAY_OFF = "ERROR_DISPLAY_OFF";

export const POST_NEW_USER_SUCCESS = "POST_NEW_USER_SUCCESS";
export const POST_NEW_USER_FAILURE = "POST_NEW_USER_FAILURE";
export const POST_LOG_IN_SUCCESS = "POST_LOG_IN_SUCCESS";
export const POST_LOG_IN_FAILURE = "POST_LOG_IN_FAILURE";
export const GET_CURRENT_USER_SUCCESS = "GET_CURRENT_USER_SUCCESS";
export const GET_CURRENT_USER_FAILURE = "GET_CURRENT_USER_FAILURE";
export const PUT_EDIT_PROFILE_SUCCESS = "PUT_EDIT_PROFILE_SUCCESS";
export const PUT_EDIT_PROFILE_FAILURE = "PUT_EDIT_PROFILE_FAILURE";

export const LOG_OUT = "LOG_OUT";
